name: pajacyk
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  adaptive_theme: 2.3.1
  flutter:
    sdk: flutter
  google_fonts: 2.3.1
  dio: 4.0.6
  fpdart: 0.0.14
  flutter_svg: 1.0.3
  intl: 0.17.0
  url_launcher: 6.1.3
  shared_preferences: 2.0.13
  timezone: 0.8.0
  rxdart: 0.27.4
  flutter_local_notifications: 9.6.1
  json_annotation: 4.4.0
  json_serializable: 6.1.5




  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  provider: ^6.0.3
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 9.0.3
  flutter_launcher_icons: ^0.9.2
  build_runner: 2.1.7
  mockingjay: 0.3.0
  mocktail: 0.3.0
  retrofit_generator: 4.0.1
  



  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  


flutter:

  assets:
    - assets/logo.png
    - assets/
    - assets/partners/

  uses-material-design: true

 
  
  

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
